workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

include:
  # 👈 1. 引入你刚刚调通语法检查的、属于你们组的纯文本模板库
  - project: mountain-high/r-pkg-template-main
    ref: main
    file: /templates/standard.gitlab-ci.yml

variables:
  # 👈 2. 消费你通过 Kaniko 亲手生产出来的内网全能 R 基础镜像
  R_CI_IMAGE: gitlab.qilu-pharma.com:5050/mountain-high/r-action-main/r-ci:latest
  
  # 👈 3. 拦截外网，强切齐鲁内网的二进制 PPM 源（拒绝源码编译，极速通关）
  CRAN_MIRROR: https://pkg-manager.qilu-pharma.com/cran/__linux__/noble/latest
  
  R_PACKAGE_DIR: .
  R_CHECK_ARGS: --no-manual
  R_CHECK_ERROR_ON: error