#' Check Visit Window Deviations
#'
#' @description
#' Check if completed visits were conducted within the specified visit window.
#' Receives planned visit data generated by \code{\link{generate_planned_visit_dates}}
#' and checks if actual visit dates are within the window range (wp_start to wp_end).
#'
#' @details
#' ## Usage Workflow
#'
#' This function is designed to work with \code{generate_planned_visit_dates}:
#'
#' ```r
#' # Step 1: Read visit schedule and generate planned visit dates
#' visitcode <- read_visitcode_file("visit_schedule.xlsx")
#' planned_dates <- generate_planned_visit_dates(data = study_data)
#'
#' # Step 2: Check visit window deviations
#' result <- check_visit_window(
#'   planned_dates = planned_dates
#' )
#' ```
#'
#' ## Out-of-Window Criteria
#'
#' For completed visits (status == "completed"):
#' - If actual visit date is within window (wp_start <= actual_date <= wp_end): Compliant
#' - If actual visit date is outside window (actual_date < wp_start or > wp_end): Deviation
#'
#' ## Window Types
#'
#' Windows are calculated by \code{generate_planned_visit_dates} based on visit schedule:
#' - +/-3d: 3 days before and after planned date
#' - +2d: Can only be delayed by 2 days
#' - -2d: Can only be early by 2 days
#'
#' @param planned_dates Data frame from \code{\link{generate_planned_visit_dates}}.
#'   Must contain: SUBJID, VISIT, VISITNUM, planned_date, wp_start, wp_end,
#'   wp_type, wp_value, actual_date, status, first_dose_date
#' @param pdno Character string specifying the protocol deviation number for this check (default: "8.4.1")
#'
#' @return List with the following components:
#'   \describe{
#'     \item{has_deviation}{Logical. TRUE if there are out-of-window visits}
#'     \item{messages}{Character vector. Deviation description messages}
#'     \item{details}{Data frame. Out-of-window visit details with columns:
#'       \itemize{
#'         \item PDNO: Protocol deviation number specified by \code{pdno} parameter
#'         \item SUBJID: Subject ID
#'         \item first_dose_date: Subject's first dose date
#'         \item VISIT: Visit name with deviation
#'         \item VISITNUM: Visit number
#'         \item planned_date: Planned visit date
#'         \item actual_date: Actual visit date
#'         \item wp_start: Window start date
#'         \item wp_end: Window end date
#'         \item wp_type: Window type
#'         \item wp_value: Window value
#'         \item deviation_days: Days deviated from planned (positive=late, negative=early)
#'         \item total_completed_visits: Total completed visits for subject
#'         \item out_of_window_count: Number of out-of-window visits
#'         \item TBNAME: Table name from planned_dates, empty if not available
#'         \item DESCRIPTION: Description of the deviation for each record
#'       }
#'     }
#'     \item{planned_visits}{Data frame. Complete input planned visit information}
#'   }
#'
#' @examples
#' \dontrun{
#' # Load data and visit schedule
#' data <- read_raw_data("path/to/data")
#' visitcode <- read_visitcode_file("path/to/visitcode.xlsx")
#'
#' # Generate planned visit dates (uses visitcode variable automatically)
#' planned_dates <- generate_planned_visit_dates(data = data)
#'
#' # Check visit window deviations
#' result <- check_visit_window(planned_dates)
#' print(result)
#'
#' # Access deviation details
#' if (result$has_deviation) {
#'   window_details <- result$details
#'   # Get subjects with out-of-window visits
#'   subjects_with_issues <- unique(window_details$SUBJID)
#' }
#' }
#'
#' @seealso
#' \code{\link{generate_planned_visit_dates}} for generating planned visit data
#' \code{\link{check_missing_visit}} for checking missing visits
#'
#' @family visit checks
#'
#' @importFrom dplyr filter bind_rows
#' @importFrom purrr map_dfr
#' @importFrom rlang .data
#' @importFrom magrittr %>%
#' @export
#'
check_visit_window <- function(planned_dates,
                               pdno = "8.4.1") {
  # Validate input parameters
  if (!is.data.frame(planned_dates)) {
    stop("'planned_dates' must be a data frame")
  }

  if (!is.character(pdno) || length(pdno) != 1) {
    stop("'pdno' must be a single character string")
  }

  # Check required columns
  required_cols <- c(
    "SUBJID", "VISIT", "VISITNUM", "planned_date",
    "wp_start", "wp_end", "wp_type", "wp_value",
    "actual_date", "status", "first_dose_date"
  )

  missing_cols <- setdiff(required_cols, names(planned_dates))
  if (length(missing_cols) > 0) {
    stop("'planned_dates' is missing required columns: ", paste(missing_cols, collapse = ", "))
  }

  # Initialize results
  results <- list(
    has_deviation = FALSE,
    messages = character(),
    details = data.frame(),
    planned_visits = planned_dates
  )

  # Only check completed visits
  completed_visits <- planned_dates %>%
    filter(.data$status == "completed" & !is.na(.data$actual_date))

  # Return early if no completed visits
  if (nrow(completed_visits) == 0) {
    class(results) <- c("visit_window_check", "list")
    return(results)
  }

  # Check out-of-window visits for each subject
  subjects <- unique(completed_visits$SUBJID)

  subject_deviations <- map_dfr(subjects, function(subj_id) {
    # Get completed visits for this subject
    subj_completed <- filter(completed_visits, .data$SUBJID == subj_id)

    # Check if each visit is within window
    # Within window: wp_start <= actual_date <= wp_end
    out_of_window <- subj_completed %>%
      # First, filter visits with valid window dates
      filter(!is.na(.data$wp_start) & !is.na(.data$wp_end)) %>%
      # Then, check if actual date is out of window
      mutate(
        is_out_of_window = case_when(
          # Early: actual date is before window start
          .data$actual_date < .data$wp_start ~ TRUE,
          # Late: actual date is after window end
          .data$actual_date > .data$wp_end ~ TRUE,
          # Within window
          TRUE ~ FALSE
        )
      ) %>%
      filter(.data$is_out_of_window) %>%
      select(-"is_out_of_window")

    # If there are out-of-window visits, build result
    if (nrow(out_of_window) > 0) {
      # Get subject's first dose date
      first_dose_date <- unique(subj_completed$first_dose_date)[1]

      # Create a record for each out-of-window visit
      return(map_dfr(seq_len(nrow(out_of_window)), function(i) {
        visit_name <- out_of_window$VISIT[i]
        visitnum <- out_of_window$VISITNUM[i]
        planned_date <- out_of_window$planned_date[i]
        actual_date <- out_of_window$actual_date[i]
        wp_start <- out_of_window$wp_start[i]
        wp_end <- out_of_window$wp_end[i]
        wp_type <- out_of_window$wp_type[i]
        wp_value <- out_of_window$wp_value[i]

        # Calculate deviation days (based on planned date)
        deviation_days <- as.numeric(actual_date - planned_date)

        # Build description text
        first_dose_str <- if (!is.na(first_dose_date)) {
          as.character(first_dose_date)
        } else {
          "未记录"
        }

        # Build window description
        if (!is.na(wp_type) && !is.na(wp_value)) {
          window_desc <- sprintf("%s%s", wp_type, wp_value)
        } else {
          window_desc <- "未定义"
        }

        deviation_text <- sprintf(
          "偏离计划时间点%d天，不在<窗口期%s>天内",
          abs(deviation_days),
          window_desc
        )

        visit_info <- sprintf(
          "%s(计划日期:%s，实际日期:%s)，%s",
          visit_name,
          planned_date,
          actual_date,
          deviation_text
        )

        data.frame(
          PDNO = pdno,
          SUBJID = subj_id,
          first_dose_date = first_dose_date,
          VISIT = visit_name,
          VISITNUM = as.numeric(visitnum),
          planned_date = planned_date,
          actual_date = actual_date,
          wp_start = wp_start,
          wp_end = wp_end,
          wp_type = wp_type,
          wp_value = wp_value,
          deviation_days = deviation_days,
          total_completed_visits = nrow(subj_completed),
          out_of_window_count = nrow(out_of_window),
          TBNAME = if ("TBNAME" %in% names(out_of_window)) {
            as.character(out_of_window$TBNAME[i])
          } else {
            ""
          },
          DESCRIPTION = sprintf(
            "受试者编号%s，首次用药时间为%s，%s",
            subj_id,
            first_dose_str,
            visit_info
          ),
          stringsAsFactors = FALSE
        )
      }))
    } else {
      return(data.frame())
    }
  })

  # Compile results
  if (nrow(subject_deviations) > 0) {
    results$has_deviation <- TRUE
    results$messages <- "基于计划访视日期检查，访视超窗"
    results$details <- subject_deviations
  }

  class(results) <- c("visit_window_check", "list")
  return(results)
}


#' Print method for visit window check results
#' @param x Object of class visit_window_check
#' @param ... Additional arguments
#' @export
print.visit_window_check <- function(x, ...) {
  pdno_display <- if (nrow(x$details) > 0) x$details$PDNO[1] else "8.4.1"
  cat(sprintf("%s 访视超窗检查\n", pdno_display))
  cat("====================================\n")
  cat(sprintf(
    "Has deviation: %s\n",
    ifelse(x$has_deviation, "YES", "NO")
  ))

  if (length(x$messages) > 0) {
    cat("\nFindings:\n")
    cat(paste("-", x$messages), sep = "\n")
  }

  if (nrow(x$details) > 0) {
    cat("\nDeviation Details:\n")
    cat(x$details$DESCRIPTION, sep = "\n")
  }
}
