#' Check Test Window Deviations
#'
#' @description
#' Check if tests were performed within the required test window at each visit.
#' Receives test-window data generated by \code{\link{generate_test_window_dates}}
#' and checks if actual test dates (or datetimes for hour rules) are within the
#' window range.
#'
#' @details
#' ## Usage Workflow
#'
#' This function is designed to work with \code{generate_test_window_dates}:
#'
#' ```r
#' # Step 1: Read test-window config and prepare test data
#' testwp <- read_testwp_file("test_wp.xlsx", sheet_name = "QL0911-302")
#' prepared_lb <- prepare_test_data(
#'   data = data, test_dataset = "LB", config = testwp,
#'   ex_time_var = "EXSTTIM", test_time_var = "LBTIM"
#' )
#'
#' # Step 2: Generate anchor dates and window ranges
#' testwp_dates <- generate_test_window_dates(prepared_lb)
#'
#' # Step 3: Check test window deviations
#' result <- check_test_window(testwp_dates)
#' ```
#'
#' ## Out-of-Window Criteria
#'
#' Only performed tests with a derivable window are checked:
#' - Missing tests (TESTDAT empty) are covered by \code{\link{check_missing_test}}
#' - Rows with NA window dates (see \code{window_status} from
#'   \code{\link{generate_test_window_dates}}) are skipped
#'
#' For each subject x visit x TESTCAT, if any test falls inside the window:
#' compliant. Otherwise one deviation record is reported, using the test
#' closest to the anchor.
#'
#' ### Day-level rules (\code{wp_unit == "d"})
#' Compare \code{TESTDAT} against \code{window_start} / \code{window_end} (Date).
#'
#' ### Hour-level rules (\code{wp_unit == "h"}, e.g. \code{EX(≤24h)})
#' Compare \code{TESTDAT}+\code{TESTTIM} against \code{window_start_dt} /
#' \code{window_end_dt} (POSIXct). Missing time defaults to 00:00:00.
#'
#' @param data Data frame from \code{\link{generate_test_window_dates}}.
#'   Must contain: SUBJID, VISIT, VISITNUM, TESTCAT, TESTDAT, wp_rule, ref,
#'   anchor_date, window_start, window_end
#' @param pdno Character string specifying the protocol deviation number for
#'   this check (default: "8.4.2")
#'
#' @return List with the following components:
#'   \describe{
#'     \item{has_deviation}{Logical. TRUE if there are out-of-window tests}
#'     \item{messages}{Character vector. Deviation description messages}
#'     \item{details}{Data frame. Out-of-window test details with columns:
#'       \itemize{
#'         \item PDNO: Protocol deviation number specified by \code{pdno} parameter
#'         \item SUBJID: Subject ID
#'         \item VISIT: Visit name
#'         \item VISITNUM: Visit number
#'         \item TESTCAT: Test category
#'         \item wp_rule: Original window rule, e.g. EX(≤24h)
#'         \item ref: Anchor type (RD/SV/EX/FD)
#'         \item wp_unit: \code{"h"} or \code{"d"}
#'         \item anchor_date: Anchor date the window is based on
#'         \item test_date: Actual test date (closest to anchor when multiple)
#'         \item window_start: Window start date
#'         \item window_end: Window end date
#'         \item deviation_days: Days from anchor (day rules; NA for hour rules)
#'         \item deviation_hours: Hours from anchor (hour rules; NA for day rules)
#'         \item TBNAME: Test dataset name, empty if not available
#'         \item DESCRIPTION: Description of the deviation for each record
#'       }
#'     }
#'   }
#'
#' @examples
#' \dontrun{
#' testwp <- read_testwp_file("test_wp.xlsx", sheet_name = "QL0911-302")
#' prepared_lb <- prepare_test_data(
#'   data = data, test_dataset = "LB", config = testwp,
#'   ex_time_var = "EXSTTIM", test_time_var = "LBTIM"
#' )
#' testwp_dates <- generate_test_window_dates(prepared_lb)
#'
#' result <- check_test_window(testwp_dates)
#' print(result)
#'
#' # Access deviation details
#' if (result$has_deviation) {
#'   window_details <- result$details
#' }
#' }
#'
#' @seealso
#' \code{\link{generate_test_window_dates}} for generating test window data
#' \code{\link{check_missing_test}} for checking missing tests
#' \code{\link{check_visit_window}} for checking visit window deviations
#'
#' @family test checks
#'
#' @importFrom dplyr filter select mutate group_by summarise first arrange bind_rows
#' @importFrom rlang .data
#' @importFrom magrittr %>%
#' @export
#'
check_test_window <- function(data,
                              pdno = "8.4.2") {
  # ============================================================================
  # Part 1: Validate input parameters
  # ============================================================================
  if (!is.data.frame(data)) {
    stop("'data' must be a data frame from generate_test_window_dates()")
  }

  if (!is.character(pdno) || length(pdno) != 1) {
    stop("'pdno' must be a single character string")
  }

  required_cols <- c(
    "SUBJID", "VISIT", "VISITNUM", "TESTCAT", "TESTDAT",
    "wp_rule", "ref", "anchor_date", "window_start", "window_end"
  )
  missing_cols <- setdiff(required_cols, names(data))
  if (length(missing_cols) > 0) {
    stop(
      "'data' is missing required columns: ", paste(missing_cols, collapse = ", "),
      "\nPlease use generate_test_window_dates() to generate window data"
    )
  }

  # ============================================================================
  # Part 2: Initialize results
  # ============================================================================
  results <- list(
    has_deviation = FALSE,
    messages = character(),
    details = data.frame()
  )

  # ============================================================================
  # Part 3: Filter checkable records
  # ============================================================================
  checked <- data %>%
    filter(!is_sas_na(.data$TESTDAT)) %>%
    mutate(
      test_date = as.Date(.data$TESTDAT),
      VISITNUM = as.character(.data$VISITNUM)
    ) %>%
    filter(
      !is.na(.data$test_date) &
        !is.na(.data$window_start) &
        !is.na(.data$window_end)
    )

  if (nrow(checked) == 0) {
    class(results) <- c("test_window_check", "list")
    return(results)
  }

  if (!"TBNAME" %in% names(checked)) {
    checked$TBNAME <- ""
  }

  # Infer wp_unit when missing
  if (!"wp_unit" %in% names(checked)) {
    if ("wp" %in% names(checked)) {
      checked$wp_unit <- ifelse(
        vapply(checked$wp, is_hour_wp, logical(1)),
        "h", "d"
      )
    } else {
      checked$wp_unit <- "d"
    }
  }
  checked$wp_unit[is.na(checked$wp_unit) | !nzchar(as.character(checked$wp_unit))] <- "d"

  # Build test datetime for hour rules
  test_time <- if ("TESTTIM" %in% names(checked)) {
    checked$TESTTIM
  } else {
    NULL
  }
  checked$test_datetime <- combine_date_time(checked$test_date, test_time)

  # ============================================================================
  # Part 4: Find out-of-window tests (day-level and hour-level)
  # ============================================================================
  day_rows <- checked %>% filter(.data$wp_unit != "h")
  hour_rows <- checked %>% filter(.data$wp_unit == "h")

  day_devs <- NULL
  hour_devs <- NULL

  if (nrow(day_rows) > 0) {
    day_devs <- day_rows %>%
      group_by(
        .data$SUBJID, .data$VISIT, .data$VISITNUM, .data$TBNAME,
        .data$TESTCAT, .data$wp_rule, .data$wp, .data$ref, .data$wp_unit,
        .data$anchor_date, .data$window_start, .data$window_end
      ) %>%
      summarise(
        in_window = any(
          .data$test_date >= first(.data$window_start) &
            .data$test_date <= first(.data$window_end)
        ),
        test_date = .data$test_date[
          which.min(abs(as.numeric(.data$test_date - first(.data$anchor_date))))
        ],
        test_datetime = as.POSIXct(NA),
        anchor_datetime = as.POSIXct(NA),
        window_start_dt = as.POSIXct(NA),
        window_end_dt = as.POSIXct(NA),
        .groups = "drop"
      ) %>%
      filter(!.data$in_window) %>%
      select(-"in_window")
  }

  if (nrow(hour_rows) > 0) {
    # Need datetime window columns from generate_test_window_dates
    has_dt <- all(c("window_start_dt", "window_end_dt", "anchor_datetime") %in% names(hour_rows))
    if (!has_dt) {
      warning(
        "Hour-level rules found but window_start_dt / window_end_dt / anchor_datetime ",
        "are missing. Re-run generate_test_window_dates() with the latest version. ",
        "Falling back to day-level comparison for these rows."
      )
      hour_devs <- hour_rows %>%
        group_by(
          .data$SUBJID, .data$VISIT, .data$VISITNUM, .data$TBNAME,
          .data$TESTCAT, .data$wp_rule, .data$wp, .data$ref, .data$wp_unit,
          .data$anchor_date, .data$window_start, .data$window_end
        ) %>%
        summarise(
          in_window = any(
            .data$test_date >= first(.data$window_start) &
              .data$test_date <= first(.data$window_end)
          ),
          test_date = .data$test_date[
            which.min(abs(as.numeric(.data$test_date - first(.data$anchor_date))))
          ],
          test_datetime = as.POSIXct(NA),
          anchor_datetime = as.POSIXct(NA),
          window_start_dt = as.POSIXct(NA),
          window_end_dt = as.POSIXct(NA),
          .groups = "drop"
        ) %>%
        filter(!.data$in_window) %>%
        select(-"in_window")
    } else {
      hour_rows <- hour_rows %>%
        filter(
          !is.na(.data$window_start_dt) &
            !is.na(.data$window_end_dt) &
            !is.na(.data$test_datetime)
        )

      if (nrow(hour_rows) > 0) {
        hour_devs <- hour_rows %>%
          group_by(
            .data$SUBJID, .data$VISIT, .data$VISITNUM, .data$TBNAME,
            .data$TESTCAT, .data$wp_rule, .data$wp, .data$ref, .data$wp_unit,
            .data$anchor_date, .data$anchor_datetime,
            .data$window_start, .data$window_end,
            .data$window_start_dt, .data$window_end_dt
          ) %>%
          summarise(
            in_window = any(
              .data$test_datetime >= first(.data$window_start_dt) &
                .data$test_datetime <= first(.data$window_end_dt)
            ),
            best_i = which.min(abs(as.numeric(
              difftime(.data$test_datetime, first(.data$anchor_datetime), units = "secs")
            ))),
            test_date = .data$test_date[best_i],
            test_datetime = .data$test_datetime[best_i],
            .groups = "drop"
          ) %>%
          filter(!.data$in_window) %>%
          select(-"in_window", -"best_i")
      }
    }
  }

  deviations <- bind_rows(day_devs, hour_devs)
  if (is.null(deviations) || nrow(deviations) == 0) {
    class(results) <- c("test_window_check", "list")
    return(results)
  }

  deviations <- deviations %>%
    arrange(.data$SUBJID, .data$VISITNUM, .data$TESTCAT)

  # ============================================================================
  # Part 5: Build results
  # ============================================================================
  ref_labels <- c(
    RD = "随机日期",
    SV = "实际访视日期",
    EX = "实际给药日期",
    FD = "首次给药日期"
  )

  details <- deviations %>%
    mutate(
      PDNO = pdno,
      VISITNUM = as.numeric(.data$VISITNUM),
      deviation_days = ifelse(
        .data$wp_unit == "h",
        NA_real_,
        as.numeric(.data$test_date - .data$anchor_date)
      ),
      deviation_hours = ifelse(
        .data$wp_unit == "h" & !is.na(.data$test_datetime) & !is.na(.data$anchor_datetime),
        as.numeric(difftime(.data$test_datetime, .data$anchor_datetime, units = "hours")),
        NA_real_
      ),
      DESCRIPTION = ifelse(
        .data$wp_unit == "h",
        sprintf(
          paste0(
            "受试者编号%s，在访视%s，检查项[%s]（检查时间:%s），锚点为%s(%s)，不在窗口期(%s至%s)范围内。"
          ),
          .data$SUBJID, .data$VISIT, .data$TESTCAT,
          format(.data$test_datetime, "%Y-%m-%d %H:%M:%S"),
          ref_labels[.data$ref],
          format(.data$anchor_datetime, "%Y-%m-%d %H:%M:%S"),
          format(.data$window_start_dt, "%Y-%m-%d %H:%M:%S"),
          format(.data$window_end_dt, "%Y-%m-%d %H:%M:%S")
        ),
        sprintf(
          paste0(
            "受试者编号%s，在访视%s，检查项[%s]（检查日期:%s），锚点为%s(%s)，不在窗口期(%s至%s)范围内。"
          ),
          .data$SUBJID, .data$VISIT, .data$TESTCAT, .data$test_date,
          ref_labels[.data$ref], format(.data$anchor_date, "%Y-%m-%d"),
          format(.data$window_start, "%Y-%m-%d"),
          format(.data$window_end, "%Y-%m-%d")
        )
      )
    ) %>%
    select(
      "PDNO", "SUBJID", "VISIT", "VISITNUM", "TESTCAT",
      "wp_rule", "ref", "wp_unit", "anchor_date", "test_date",
      "window_start", "window_end", "deviation_days", "deviation_hours",
      "TBNAME", "DESCRIPTION"
    )

  results$has_deviation <- TRUE
  results$messages <- sprintf(
    "基于检查项窗口规则检查，检查项超窗 %d 条。",
    nrow(details)
  )
  results$details <- details

  class(results) <- c("test_window_check", "list")
  return(results)
}


#' Print method for test window check results
#' @param x Object of class test_window_check
#' @param ... Additional arguments
#' @export
print.test_window_check <- function(x, ...) {
  pdno_display <- if (nrow(x$details) > 0) x$details$PDNO[1] else "8.4.2"
  cat(sprintf("%s 检查项超窗检查\n", pdno_display))
  cat("====================================\n")
  cat(sprintf(
    "Has deviation: %s\n",
    ifelse(x$has_deviation, "YES", "NO")
  ))

  if (length(x$messages) > 0) {
    cat("\nFindings:\n")
    cat(paste("-", x$messages), sep = "\n")
  }

  if (nrow(x$details) > 0) {
    cat("\nDeviation Details:\n")
    cat(x$details$DESCRIPTION, sep = "\n")
  }
}
